name: Deploy Laravel Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar entorno PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Instalar dependencias de Composer
      run: composer install --no-dev --optimize-autoloader

    - name: Configurar el archivo .env
      run: |
        cp .env.production .env

    - name: Configure env
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_DESTINATION: ${{ secrets.FTP_DESTINATION }}
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache 
        php artisan optimize

    - name: Subir al servidor via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DESTINATION }}