services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: #Nombre de la app -> Modificar
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root_user
      DB_PASSWORD: root_pass
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: # Nombre del server -> Modificar
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: # Nombre de la db -> Modificar
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root_pass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1
