services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./prueba:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root_user
      DB_PASSWORD: root
    depends_on:
      - db

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./prueba:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    container_name: vite_video
    working_dir: /var/www
    command: npm run dev
    volumes:
      - ./prueba:/var/www
      - /var/www/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root_user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

networks:
  default:
    name: laravel_network